'use client';
import { useEffect, useState } from 'react';
type Policy={businessName:string;contactEmail:string;cancellationPolicy:string;refundPolicy:string;privacyRetention:string;version:string};
export default function LegalPage(){
 const [policy,setPolicy]=useState<Policy|null>(null),[error,setError]=useState('');
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('operation');if(!id){setError('Choose the policy link provided with your service invoice for the service provider’s policies.');return;}fetch(`/api/legal/${encodeURIComponent(id)}`).then(async r=>{if(!r.ok)throw Error('This operation has not published its payment policies. Checkout is unavailable until they are approved.');setPolicy(await r.json());}).catch(e=>setError(e.message));},[]);
 return <main style={{maxWidth:820,margin:'40px auto',padding:24,lineHeight:1.7}}><h1>Terms of service & privacy</h1><p>Version September 25, 2026</p>
 {error&&<p role="alert">{error}</p>}
 <h2>Using Dive Schedule</h2><p>Dive Schedule is operations software used by the service operation identified on your invoice. Your hull-cleaning contract is with that operation. Only use accounts and records you are authorized to access. Keep login credentials secure and tell your service provider about incorrect or unauthorized activity.</p>
 <h2>Service scope and payment</h2><p>Your accepted quote or service agreement defines the work, schedule and price. A payment link is for the displayed service amount in US dollars. Review the amount and business name before paying. Additional work requires separate agreement. A checkout return screen is not a receipt: payment is confirmed after verification with the payment provider.</p>
 <h2>Access, scheduling and conditions</h2><p>Provide accurate vessel and access information and permission to perform the agreed work. Contact the operation about marina restrictions, vessel movement, damage, hazards or access changes. Weather, unsafe conditions and unavailable access may require rescheduling. A service report describes work recorded by the operation and is not a warranty of vessel condition or a substitute for a specialist inspection.</p>
 {policy&&<><h2>Your service provider</h2><p>{policy.businessName}<br/><a href={`mailto:${policy.contactEmail}`}>{policy.contactEmail}</a></p><h2>Cancellation and rescheduling</h2><p style={{whiteSpace:'pre-wrap'}}>{policy.cancellationPolicy}</p><h2>Refunds and disputes</h2><p style={{whiteSpace:'pre-wrap'}}>{policy.refundPolicy}</p></>}
 <h2>Privacy notice</h2><p>The operation uses customer contact information, vessel/site details, service instructions, inspection answers, service photos and payment references to schedule and document work, collect payment, respond to questions and maintain business records. Staff account identifiers, permissions and activity records support access control and security.</p>
 <p>Card and wallet payment details are entered into Stripe or PayPal/Venmo interfaces. Dive Schedule stores payment identifiers, amounts and status; it does not ask staff to store complete card numbers or wallet passwords. Hosting, identity and payment providers process information needed to provide these services. Their own privacy terms also apply: <a href="https://stripe.com/privacy">Stripe</a> and <a href="https://www.paypal.com/us/legalhub/paypal/privacy-full">PayPal</a>.</p>
 <p>Do not use shared devices for confidential service records. Do not upload unrelated sensitive information or photographs you lack authority to share. No payment-provider script is needed to read this policy page; opening a payment page may load the chosen provider’s services.</p>
 {policy&&<><h3>Retention and requests</h3><p style={{whiteSpace:'pre-wrap'}}>{policy.privacyRetention}</p><p>Contact <a href={`mailto:${policy.contactEmail}`}>{policy.contactEmail}</a> for access, correction, deletion requests or privacy questions. Some information may need to be retained for transaction records, disputes or legal requirements.</p></>}
 <h2>Records and communications</h2><p>You may receive service and payment communications needed to complete your transaction. This does not enroll you in marketing. Tell the operation promptly if a report or payment appears incorrect. Contact the operation to request a record correction.</p>
 <h2>Rights and policy changes</h2><p>These terms do not remove rights that cannot lawfully be waived. Separately agreed service terms and applicable law continue to apply. Material policy changes will be identified by a new version; the version accepted for a payment is recorded with that transaction.</p>
 </main>;
}
